# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
clair:
  database:
    type: pgsql
    options:
      source: "postgres://postgres:RhtBttYV22D3DWVgXIg1WGewDCrx19vlvfnxciWBAhxSrHgvvv6I6cxPecEaHX4y@example-cluster-postgres.postgres-cluster-1.svc.cluster.local:5432/postgres?sslmode=disable"
      # Number of elements kept in the cache
      # Values unlikely to change (e.g. namespaces) are cached in order to save prevent needless roundtrips to the database.
      cachesize: 16384
  api:
    # API server port
    port: 6060
    healthport: 6061
    # Deadline before an API request will respond with a 503
    timeout: 300s
  updater:
    interval: 12h
