# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

name: qa
kind: pipeline
type: docker

node:
   performance: low

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

environment:
  MISE_DATA_DIR: /mise-data

volumes:
  - name: mise-cache
    host:
      path: /root/mise_data_dir

steps: # qa
  - name: install-tools
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    volumes:
      - name: mise-cache
        path: /mise-data
    commands:
      - mise install
      - eval "$(mise activate bash --shims)"

  - name: license-check
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    depends_on:
      - install-tools
    volumes:
      - name: mise-cache
        path: /mise-data
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run license-check

  - name: render
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    depends_on:
      - license-check
    volumes:
      - name: mise-cache
        path: /mise-data
    commands:
      - eval "$(mise activate bash --shims)"
      - kustomize build katalog/harbor/distributions/full-harbor > distribution.yml

  - name: check-deprecated-apis
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    depends_on:
      - render
    volumes:
      - name: mise-cache
        path: /mise-data
    commands:
      - eval "$(mise activate bash --shims)"
      # we use --ignore-deprecations because we don't want the CI to fail when the API has not been removed yet.
      - pluto detect distribution.yml --ignore-deprecations --target-versions=k8s=v1.34.0

---

name: e2e-kubernetes-1.30
kind: pipeline
type: docker

environment:
  CLUSTER_VERSION: v1.30.4
  MISE_DATA_DIR: /mise-data
  TEST_DOMAIN: "127.0.0.1.nip.io"

depends_on:
  - qa

clone:
  depth: 1

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: mise-cache
    host:
      path: /root/mise_data_dir

steps:
  - name: generate-kind-config
    image: alpine:latest
    pull: always
    commands:
      - sh ./katalog/tests/harbor/config/generate-template.sh $${CLUSTER_VERSION}

  - name: install-tools
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    volumes:
      - name: mise-cache
        path: /mise-data
    commands:
      - mise install
      - mise use kubectl@$${CLUSTER_VERSION}
      - eval "$(mise activate bash --shims)"

  - name: create-kind-cluster
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    depends_on:
      - install-tools
      - generate-kind-config
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: mise-cache
        path: /mise-data
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run create-kind-cluster

  - name: e2e-setup
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - create-kind-cluster
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run e2e-setup

  - name: e2e-vulns
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - e2e-setup
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run e2e-vulns

  - name: e2e-replication
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - e2e-setup
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run e2e-replication

  - name: e2e-registry
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - e2e-setup
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run e2e-registry

  - name: delete-kind-cluster
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: mise-cache
        path: /mise-data
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run delete-kind-cluster
    depends_on:
      - e2e-vulns
      - e2e-replication
      - e2e-registry
    when:
      status:
        - success
        - failure

---

name: e2e-kubernetes-1.31
kind: pipeline
type: docker

environment:
  CLUSTER_VERSION: v1.31.0
  MISE_DATA_DIR: /mise-data
  TEST_DOMAIN: "127.0.0.1.nip.io"

depends_on:
  - qa

clone:
  depth: 1

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: mise-cache
    host:
      path: /root/mise_data_dir

steps:
  - name: generate-kind-config
    image: alpine:latest
    pull: always
    commands:
      - sh ./katalog/tests/harbor/config/generate-template.sh $${CLUSTER_VERSION}

  - name: install-tools
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    volumes:
      - name: mise-cache
        path: /mise-data
    commands:
      - mise install
      - mise use kubectl@$${CLUSTER_VERSION}
      - eval "$(mise activate bash --shims)"

  - name: create-kind-cluster
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    depends_on:
      - install-tools
      - generate-kind-config
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: mise-cache
        path: /mise-data
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run create-kind-cluster

  - name: e2e-setup
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - create-kind-cluster
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run e2e-setup

  - name: e2e-vulns
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - e2e-setup
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run e2e-vulns

  - name: e2e-replication
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - e2e-setup
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run e2e-replication

  - name: e2e-registry
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - e2e-setup
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run e2e-registry

  - name: delete-kind-cluster
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: mise-cache
        path: /mise-data
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run delete-kind-cluster
    depends_on:
      - e2e-vulns
      - e2e-replication
      - e2e-registry
    when:
      status:
        - success
        - failure

---

name: e2e-kubernetes-1.32
kind: pipeline
type: docker

environment:
  CLUSTER_VERSION: v1.32.2
  MISE_DATA_DIR: /mise-data
  TEST_DOMAIN: "127.0.0.1.nip.io"

depends_on:
  - qa

clone:
  depth: 1

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: mise-cache
    host:
      path: /root/mise_data_dir

steps:
  - name: generate-kind-config
    image: alpine:latest
    pull: always
    commands:
      - sh ./katalog/tests/harbor/config/generate-template.sh $${CLUSTER_VERSION}

  - name: install-tools
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    volumes:
      - name: mise-cache
        path: /mise-data
    commands:
      - mise install
      - mise use kubectl@$${CLUSTER_VERSION}
      - eval "$(mise activate bash --shims)"

  - name: create-kind-cluster
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    depends_on:
      - install-tools
      - generate-kind-config
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: mise-cache
        path: /mise-data
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run create-kind-cluster

  - name: e2e-setup
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - create-kind-cluster
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run e2e-setup

  - name: e2e-vulns
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - e2e-setup
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run e2e-vulns

  - name: e2e-replication
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - e2e-setup
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run e2e-replication

  - name: e2e-registry
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - e2e-setup
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run e2e-registry

  - name: delete-kind-cluster
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: mise-cache
        path: /mise-data
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run delete-kind-cluster
    depends_on:
      - e2e-vulns
      - e2e-replication
      - e2e-registry
    when:
      status:
        - success
        - failure

---

name: e2e-kubernetes-1.33
kind: pipeline
type: docker

environment:
  CLUSTER_VERSION: v1.33.2
  MISE_DATA_DIR: /mise-data
  TEST_DOMAIN: "127.0.0.1.nip.io"

depends_on:
  - qa

clone:
  depth: 1

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: mise-cache
    host:
      path: /root/mise_data_dir

steps:
  - name: generate-kind-config
    image: alpine:latest
    pull: always
    commands:
      - sh ./katalog/tests/harbor/config/generate-template.sh $${CLUSTER_VERSION}

  - name: install-tools
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    volumes:
      - name: mise-cache
        path: /mise-data
    commands:
      - mise install
      - mise use kubectl@$${CLUSTER_VERSION}
      - eval "$(mise activate bash --shims)"

  - name: create-kind-cluster
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    depends_on:
      - install-tools
      - generate-kind-config
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: mise-cache
        path: /mise-data
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run create-kind-cluster

  - name: e2e-setup
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - create-kind-cluster
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run e2e-setup

  - name: e2e-vulns
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - e2e-setup
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run e2e-vulns

  - name: e2e-replication
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - e2e-setup
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run e2e-replication

  - name: e2e-registry
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - e2e-setup
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run e2e-registry

  - name: delete-kind-cluster
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: mise-cache
        path: /mise-data
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run delete-kind-cluster
    depends_on:
      - e2e-vulns
      - e2e-replication
      - e2e-registry
    when:
      status:
        - success
        - failure

---

name: e2e-kubernetes-1.34
kind: pipeline
type: docker

environment:
  CLUSTER_VERSION: v1.34.0
  MISE_DATA_DIR: /mise-data
  TEST_DOMAIN: "127.0.0.1.nip.io"

depends_on:
  - qa

clone:
  depth: 1

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: mise-cache
    host:
      path: /root/mise_data_dir

steps:
  - name: generate-kind-config
    image: alpine:latest
    pull: always
    commands:
      - sh ./katalog/tests/harbor/config/generate-template.sh $${CLUSTER_VERSION}

  - name: install-tools
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    volumes:
      - name: mise-cache
        path: /mise-data
    commands:
      - mise install
      - mise use kubectl@$${CLUSTER_VERSION}
      - eval "$(mise activate bash --shims)"

  - name: create-kind-cluster
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    depends_on:
      - install-tools
      - generate-kind-config
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: mise-cache
        path: /mise-data
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run create-kind-cluster

  - name: e2e-setup
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - create-kind-cluster
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run e2e-setup

  - name: e2e-vulns
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - e2e-setup
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run e2e-vulns

  - name: e2e-replication
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - e2e-setup
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run e2e-replication

  - name: e2e-registry
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - e2e-setup
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run e2e-registry

  - name: delete-kind-cluster
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: mise-cache
        path: /mise-data
    commands:
      - eval "$(mise activate bash --shims)"
      - mise run delete-kind-cluster
    depends_on:
      - e2e-vulns
      - e2e-replication
      - e2e-registry
    when:
      status:
        - success
        - failure

---

name: release
kind: pipeline
type: docker

depends_on:
  - e2e-kubernetes-1.30
  - e2e-kubernetes-1.31
  - e2e-kubernetes-1.32
  - e2e-kubernetes-1.33
  - e2e-kubernetes-1.34

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**
    exclude:
      - refs/tags/e2e-**

steps:
  - name: prepare-tar-gz
    image: alpine:latest
    pull: always
    depends_on: [clone]
    commands:
      - tar -zcvf fury-kubernetes-registry-${DRONE_TAG}.tar.gz katalog/ LICENSE README.md
    when:
      ref:
        include:
          - refs/tags/**

  - name: prepare-release-notes
    image: quay.io/sighup/fury-release-notes-plugin:3.7_2.8.4
    pull: always
    depends_on: [clone]
    settings:
      release_notes_file_path: release-notes.md
    when:
      ref:
        include:
          - refs/tags/**

  - name: publish-prerelease
    image: plugins/github-release
    pull: always
    depends_on:
      - prepare-tar-gz
      - prepare-release-notes
    settings:
      api_key:
        from_secret: github_token
      file_exists: overwrite
      files:
        - fury-kubernetes-registry-${DRONE_TAG}.tar.gz
      prerelease: true
      overwrite: true
      title: "Preview ${DRONE_TAG}"
      note: release-notes.md
      checksum:
        - md5
        - sha256
    when:
      ref:
        include:
          - refs/tags/v**-rc**

  - name: publish-stable
    image: plugins/github-release
    pull: always
    depends_on:
      - prepare-tar-gz
      - prepare-release-notes
    settings:
      api_key:
        from_secret: github_token
      file_exists: overwrite
      files:
        - fury-kubernetes-registry-${DRONE_TAG}.tar.gz
      prerelease: false
      overwrite: true
      title: "Release ${DRONE_TAG}"
      note: release-notes.md
      checksum:
        - md5
        - sha256
    when:
      ref:
        exclude:
          - refs/tags/v**-rc**
        include:
          - refs/tags/v**
