# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

kind: pipeline
name: license

steps:
  - name: check
    image: docker.io/library/golang:1.14.3
    pull: always
    commands:
      - go get -u github.com/google/addlicense
      - addlicense -c "SIGHUP s.r.l" -v -l bsd --check .
---
kind: pipeline
name: policeman

platform:
  os: linux
  arch: amd64

depends_on:
  - license

steps:
  - name: lint
    image: quay.io/sighup/policeman
    pull: always
    depends_on:
      - clone

  - name: render
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.18.8_3.3.0_2.4.1
    pull: always
    depends_on:
      - clone
    commands:
      - kustomize build katalog/harbor/distributions/full-harbor > distribution.yml

  - name: deprek8ion
    image: eu.gcr.io/swade1987/deprek8ion:1.1.31
    pull: always
    depends_on:
      - render
    commands:
      - /conftest test -p /policies distribution.yml
---
kind: pipeline
name: e2e-kubernetes-1.16

depends_on:
  - policeman

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**

steps:
  - name: init
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.3.2
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ clone ]
    settings:
      action: custom-cluster-116
      pipeline_id: cluster-116
      local_kind_config_path: katalog/tests/harbor/config/kind-config
      cluster_version: '1.16.9'
      instance_path: /shared
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
    when:
      ref:
        include:
          - refs/tags/**

  - name: e2e-setup
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.16.15_3.3.0_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ init ]
    environment:
      DYNAMIC_DNS_SERVICE:
        from_secret: dynamic_dns_service
    commands:
      - export KUBECONFIG=/shared/kube/kubeconfig-116
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export EXTERNAL_DNS="$INSTANCE_IP.$DYNAMIC_DNS_SERVICE"
      - bats -t katalog/tests/harbor/setup.sh
    when:
      ref:
        include:
          - refs/tags/**

  - name: e2e-vulns
    image: docker:dind
    pull: always
    volumes:
    - name: shared
      path: /shared
    - name: dockersock
      path: /var/run/docker.sock
    environment:
      DYNAMIC_DNS_SERVICE:
        from_secret: dynamic_dns_service
    depends_on: [ e2e-setup ]
    commands:
      - apk add curl jq git bash ca-certificates
      - git clone https://github.com/bats-core/bats-core.git /tmp/bats-core
      - cd /tmp/bats-core
      - git checkout v1.1.0
      - ./install.sh /usr/local
      - cd -
      - export KUBECONFIG=/shared/kube/kubeconfig-116
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export EXTERNAL_DNS="$INSTANCE_IP.$DYNAMIC_DNS_SERVICE"
      - bats -t katalog/tests/harbor/vulns.sh
    when:
      ref:
        include:
          - refs/tags/**

  - name: e2e-chartmuseum
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.16.15_3.3.0_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    environment:
      DYNAMIC_DNS_SERVICE:
        from_secret: dynamic_dns_service
    depends_on: [ e2e-setup ]
    commands:
      - export KUBECONFIG=/shared/kube/kubeconfig-116
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export EXTERNAL_DNS="$INSTANCE_IP.$DYNAMIC_DNS_SERVICE"
      - bats -t katalog/tests/harbor/chartmuseum.sh
    when:
      ref:
        include:
          - refs/tags/**

  - name: e2e-replication
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.16.15_3.3.0_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    environment:
      DYNAMIC_DNS_SERVICE:
        from_secret: dynamic_dns_service
    depends_on: [ e2e-setup ]
    commands:
      - export KUBECONFIG=/shared/kube/kubeconfig-116
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export EXTERNAL_DNS="$INSTANCE_IP.$DYNAMIC_DNS_SERVICE"
      - bats -t katalog/tests/harbor/replication.sh
    when:
      ref:
        include:
          - refs/tags/**

  - name: e2e-registry
    image: docker:dind
    pull: always
    volumes:
    - name: shared
      path: /shared
    - name: dockersock
      path: /var/run/docker.sock
    environment:
      DYNAMIC_DNS_SERVICE:
        from_secret: dynamic_dns_service
    depends_on: [ e2e-setup ]
    commands:
      - apk add curl jq git bash ca-certificates
      - git clone https://github.com/bats-core/bats-core.git /tmp/bats-core
      - cd /tmp/bats-core
      - git checkout v1.1.0
      - ./install.sh /usr/local
      - cd -
      - export KUBECONFIG=/shared/kube/kubeconfig-116
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export EXTERNAL_DNS="$INSTANCE_IP.$DYNAMIC_DNS_SERVICE"
      - bats -t katalog/tests/harbor/registry.sh
      - bats -t katalog/tests/harbor/registry-notary.sh
    when:
      ref:
        include:
          - refs/tags/**

  - name: destroy
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.3.2
    pull: always
    depends_on: [ e2e-vulns, e2e-chartmuseum, e2e-replication, e2e-registry ]
    settings:
      action: destroy
      pipeline_id: cluster-116
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
    when:
      status:
      - success
      - failure

volumes:
- name: shared
  temp: {}
- name: dockersock
  host:
    path: /var/run/docker.sock
---
kind: pipeline
name: e2e-kubernetes-1.17

depends_on:
  - policeman

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**

steps:
  - name: init
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.3.2
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ clone ]
    settings:
      action: custom-cluster-117
      pipeline_id: cluster-117
      local_kind_config_path: katalog/tests/harbor/config/kind-config
      cluster_version: '1.17.5'
      instance_path: /shared
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
    when:
      ref:
        include:
          - refs/tags/**

  - name: e2e-setup
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.17.11_3.3.0_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ init ]
    environment:
      DYNAMIC_DNS_SERVICE:
        from_secret: dynamic_dns_service
    commands:
      - export KUBECONFIG=/shared/kube/kubeconfig-117
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export EXTERNAL_DNS="$INSTANCE_IP.$DYNAMIC_DNS_SERVICE"
      - bats -t katalog/tests/harbor/setup.sh
    when:
      ref:
        include:
          - refs/tags/**

  - name: e2e-vulns
    image: docker:dind
    pull: always
    volumes:
    - name: shared
      path: /shared
    - name: dockersock
      path: /var/run/docker.sock
    environment:
      DYNAMIC_DNS_SERVICE:
        from_secret: dynamic_dns_service
    depends_on: [ e2e-setup ]
    commands:
      - apk add curl jq git bash ca-certificates
      - git clone https://github.com/bats-core/bats-core.git /tmp/bats-core
      - cd /tmp/bats-core
      - git checkout v1.1.0
      - ./install.sh /usr/local
      - cd -
      - export KUBECONFIG=/shared/kube/kubeconfig-117
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export EXTERNAL_DNS="$INSTANCE_IP.$DYNAMIC_DNS_SERVICE"
      - bats -t katalog/tests/harbor/vulns.sh
    when:
      ref:
        include:
          - refs/tags/**

  - name: e2e-chartmuseum
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.17.11_3.3.0_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    environment:
      DYNAMIC_DNS_SERVICE:
        from_secret: dynamic_dns_service
    depends_on: [ e2e-setup ]
    commands:
      - export KUBECONFIG=/shared/kube/kubeconfig-117
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export EXTERNAL_DNS="$INSTANCE_IP.$DYNAMIC_DNS_SERVICE"
      - bats -t katalog/tests/harbor/chartmuseum.sh
    when:
      ref:
        include:
          - refs/tags/**

  - name: e2e-replication
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.17.11_3.3.0_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    environment:
      DYNAMIC_DNS_SERVICE:
        from_secret: dynamic_dns_service
    depends_on: [ e2e-setup ]
    commands:
      - export KUBECONFIG=/shared/kube/kubeconfig-117
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export EXTERNAL_DNS="$INSTANCE_IP.$DYNAMIC_DNS_SERVICE"
      - bats -t katalog/tests/harbor/replication.sh
    when:
      ref:
        include:
          - refs/tags/**

  - name: e2e-registry
    image: docker:dind
    pull: always
    volumes:
    - name: shared
      path: /shared
    - name: dockersock
      path: /var/run/docker.sock
    environment:
      DYNAMIC_DNS_SERVICE:
        from_secret: dynamic_dns_service
    depends_on: [ e2e-setup ]
    commands:
      - apk add curl jq git bash ca-certificates
      - git clone https://github.com/bats-core/bats-core.git /tmp/bats-core
      - cd /tmp/bats-core
      - git checkout v1.1.0
      - ./install.sh /usr/local
      - cd -
      - export KUBECONFIG=/shared/kube/kubeconfig-117
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export EXTERNAL_DNS="$INSTANCE_IP.$DYNAMIC_DNS_SERVICE"
      - bats -t katalog/tests/harbor/registry.sh
      - bats -t katalog/tests/harbor/registry-notary.sh
    when:
      ref:
        include:
          - refs/tags/**

  - name: destroy
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.3.2
    pull: always
    depends_on: [ e2e-vulns, e2e-chartmuseum, e2e-replication, e2e-registry ]
    settings:
      action: destroy
      pipeline_id: cluster-117
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
    when:
      status:
      - success
      - failure

volumes:
- name: shared
  temp: {}
- name: dockersock
  host:
    path: /var/run/docker.sock
---
kind: pipeline
name: e2e-kubernetes-1.18

depends_on:
  - policeman

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**

steps:
  - name: init
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.3.2
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ clone ]
    settings:
      action: custom-cluster-118
      pipeline_id: cluster-118
      local_kind_config_path: katalog/tests/harbor/config/kind-config
      cluster_version: '1.18.8'
      instance_path: /shared
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
    when:
      ref:
        include:
          - refs/tags/**

  - name: e2e-setup
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.18.8_3.3.0_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ init ]
    environment:
      DYNAMIC_DNS_SERVICE:
        from_secret: dynamic_dns_service
    commands:
      - export KUBECONFIG=/shared/kube/kubeconfig-118
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export EXTERNAL_DNS="$INSTANCE_IP.$DYNAMIC_DNS_SERVICE"
      - bats -t katalog/tests/harbor/setup.sh
    when:
      ref:
        include:
          - refs/tags/**

  - name: e2e-vulns
    image: docker:dind
    pull: always
    volumes:
    - name: shared
      path: /shared
    - name: dockersock
      path: /var/run/docker.sock
    environment:
      DYNAMIC_DNS_SERVICE:
        from_secret: dynamic_dns_service
    depends_on: [ e2e-setup ]
    commands:
      - apk add curl jq git bash ca-certificates
      - git clone https://github.com/bats-core/bats-core.git /tmp/bats-core
      - cd /tmp/bats-core
      - git checkout v1.1.0
      - ./install.sh /usr/local
      - cd -
      - export KUBECONFIG=/shared/kube/kubeconfig-118
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export EXTERNAL_DNS="$INSTANCE_IP.$DYNAMIC_DNS_SERVICE"
      - bats -t katalog/tests/harbor/vulns.sh
    when:
      ref:
        include:
          - refs/tags/**

  - name: e2e-chartmuseum
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.18.8_3.3.0_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    environment:
      DYNAMIC_DNS_SERVICE:
        from_secret: dynamic_dns_service
    depends_on: [ e2e-setup ]
    commands:
      - export KUBECONFIG=/shared/kube/kubeconfig-118
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export EXTERNAL_DNS="$INSTANCE_IP.$DYNAMIC_DNS_SERVICE"
      - bats -t katalog/tests/harbor/chartmuseum.sh
    when:
      ref:
        include:
          - refs/tags/**

  - name: e2e-replication
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.18.8_3.3.0_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    environment:
      DYNAMIC_DNS_SERVICE:
        from_secret: dynamic_dns_service
    depends_on: [ e2e-setup ]
    commands:
      - export KUBECONFIG=/shared/kube/kubeconfig-118
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export EXTERNAL_DNS="$INSTANCE_IP.$DYNAMIC_DNS_SERVICE"
      - bats -t katalog/tests/harbor/replication.sh
    when:
      ref:
        include:
          - refs/tags/**

  - name: e2e-registry
    image: docker:dind
    pull: always
    volumes:
    - name: shared
      path: /shared
    - name: dockersock
      path: /var/run/docker.sock
    environment:
      DYNAMIC_DNS_SERVICE:
        from_secret: dynamic_dns_service
    depends_on: [ e2e-setup ]
    commands:
      - apk add curl jq git bash ca-certificates
      - git clone https://github.com/bats-core/bats-core.git /tmp/bats-core
      - cd /tmp/bats-core
      - git checkout v1.1.0
      - ./install.sh /usr/local
      - cd -
      - export KUBECONFIG=/shared/kube/kubeconfig-118
      - export INSTANCE_IP=$(cat /shared/machine/ip)
      - export EXTERNAL_DNS="$INSTANCE_IP.$DYNAMIC_DNS_SERVICE"
      - bats -t katalog/tests/harbor/registry.sh
      - bats -t katalog/tests/harbor/registry-notary.sh
    when:
      ref:
        include:
          - refs/tags/**

  - name: destroy
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.3.2
    pull: always
    depends_on: [ e2e-vulns, e2e-chartmuseum, e2e-replication, e2e-registry ]
    settings:
      action: destroy
      pipeline_id: cluster-118
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
    when:
      status:
      - success
      - failure

volumes:
- name: shared
  temp: {}
- name: dockersock
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: release

depends_on:
  - e2e-kubernetes-1.16
  - e2e-kubernetes-1.17
  - e2e-kubernetes-1.18

platform:
  os: linux
  arch: amd64

trigger:
  ref:
    include:
      - refs/tags/**

steps:
  - name: prepare-tar-gz
    image: alpine:latest
    pull: always
    depends_on: [ clone ]
    commands:
      - tar -zcvf fury-kubernetes-registry-${DRONE_TAG}.tar.gz katalog/ LICENSE README.md
    when:
      ref:
        include:
          - refs/tags/**

  - name: prepare-release-notes
    image: quay.io/sighup/fury-release-notes-plugin:3.7_2.8.4
    pull: always
    depends_on: [ clone ]
    settings:
      release_notes_file_path: release-notes.md
    when:
      ref:
        include:
          - refs/tags/**

  - name: publish-prerelease
    image: plugins/github-release
    pull: always
    depends_on:
      - prepare-tar-gz
      - prepare-release-notes
    settings:
      api_key:
        from_secret: github_token
      file_exists: overwrite
      files:
        - fury-kubernetes-registry-${DRONE_TAG}.tar.gz
      prerelease: true
      overwrite: true
      title: "Preview ${DRONE_TAG}"
      note: release-notes.md
      checksum:
        - md5
        - sha256
    when:
      ref:
        include:
          - refs/tags/v**-rc**

  - name: publish-stable
    image: plugins/github-release
    pull: always
    depends_on:
      - prepare-tar-gz
      - prepare-release-notes
    settings:
      api_key:
        from_secret: github_token
      file_exists: overwrite
      files:
        - fury-kubernetes-registry-${DRONE_TAG}.tar.gz
      prerelease: false
      overwrite: true
      title: "Release ${DRONE_TAG}"
      note: release-notes.md
      checksum:
        - md5
        - sha256
    when:
      ref:
        exclude:
          - refs/tags/v**-rc**
        include:
          - refs/tags/v**
