---
- op: add
  path: "/metadata/annotations/kubernetes.io~1ingress.class"
  value: "my-ingress-class"

- op: add
  path: "/metadata/annotations/forecastle.stakater.com~1expose"
  value: "true"

- op: add
  path: "/metadata/annotations/forecastle.stakater.com~1appName"
  value: "Harbor"

- op: add
  path: "/metadata/annotations/forecastle.stakater.com~1icon"
  value: "https://goharbor.io/img/logos/harbor-icon-color.png"

- op: replace
  path: /spec/rules/0/host
  value: core.myharbor.domain

- op: replace
  path: /spec/rules/1/host
  value: notary.myharbor.domain
