---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-chartmuseum
  labels:
    app: harbor
    component: chartmuseum
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
