---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deploy.yml
  - svc.yml

images:
  - name: goharbor/harbor-jobservice
    newTag: v2.0.0

configMapGenerator:
  - name: jobservice
    files:
      - config.yml=config/config.yml
    literals:
      - CORE_URL=http://core
      - REGISTRY_CONTROLLER_URL=http://registry
      - LOG_LEVEL=info
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - NO_PROXY=core,jobservice,database,chartmuseum,clair,notary-server,notary-signer,registry,portal,127.0.0.1,localhost,.local,.internal

secretGenerator:
  - name: jobservice
    literals:
      - secret=Gx6IsNtY4NdWoK0u
      - REGISTRY_CREDENTIAL_USERNAME=harbor_registry_user
      - REGISTRY_CREDENTIAL_PASSWORD=DhQTxjwUAyUZHaMABvm90dGAJMDX5jaa
