---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../chartmuseum
  - ../../clair
  - ../../core
  - ../../notary
  - ../../nginx
  - ../../jobservice
  - ../../portal
  - ../../redis
  - ../../registry
