---
# Source: harbor/templates/notary/notary-server.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-harbor-notary-server
  labels:
    heritage: Tiller
    release: release-name
    chart: harbor
    app: "harbor"
    component: notary-server
spec:
  replicas: 1
  selector:
    matchLabels:
      release: release-name
      app: "harbor"
      component: notary-server
  template:
    metadata:
      labels:
        heritage: Tiller
        release: release-name
        chart: harbor
        app: "harbor"
        component: notary-server
      annotations:
        checksum/secret: 0a73718c226d40401734af7626c4036e9a71180405884e44f28225412c01e8f5
        checksum/secret-core: 50c4d8c8ce749d2aed69a061ddf0fb62935a45d5c4f6938754dad950a1fd4acd
    spec:
      securityContext:
        fsGroup: 10000
      containers:
        - name: notary-server
          image: goharbor/notary-server-photon:v0.6.1-v1.10.1
          imagePullPolicy: IfNotPresent
          env:
            - name: MIGRATIONS_PATH
              value: migrations/server/postgresql
            - name: DB_URL
              value: postgres://postgres:changeit@release-name-harbor-database:5432/notaryserver?sslmode=disable
          volumeMounts:
            - name: config
              mountPath: /etc/notary/server-config.postgres.json
              subPath: server.json
            - name: token-service-certificate
              mountPath: /root.crt
              subPath: tls.crt
            - name: signer-certificate
              mountPath: /etc/ssl/notary/ca.crt
              subPath: ca.crt
      volumes:
        - name: config
          secret:
            secretName: "release-name-harbor-notary-server"
        - name: token-service-certificate
          secret:
            secretName: release-name-harbor-core
        - name: signer-certificate
          secret:
            secretName: release-name-harbor-notary-server

---
# Source: harbor/templates/notary/notary-signer.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-harbor-notary-signer
  labels:
    heritage: Tiller
    release: release-name
    chart: harbor
    app: "harbor"
    component: notary-signer
spec:
  replicas: 1
  selector:
    matchLabels:
      release: release-name
      app: "harbor"
      component: notary-signer
  template:
    metadata:
      labels:
        heritage: Tiller
        release: release-name
        chart: harbor
        app: "harbor"
        component: notary-signer
      annotations:
        checksum/secret: 52d5618d6985c8fba184c3006eed61f4b716b81fb0bfda7488ec9da1d145fec1
    spec:
      securityContext:
        fsGroup: 10000
      containers:
        - name: notary-signer
          image: goharbor/notary-signer-photon:v0.6.1-v1.10.1
          imagePullPolicy: IfNotPresent
          env:
            - name: MIGRATIONS_PATH
              value: migrations/signer/postgresql
            - name: DB_URL
              value: postgres://postgres:changeit@release-name-harbor-database:5432/notarysigner?sslmode=disable
            - name: NOTARY_SIGNER_DEFAULTALIAS
              value: defaultalias
          volumeMounts:
            - name: config
              mountPath: /etc/notary/signer-config.postgres.json
              subPath: signer.json
            - name: signer-certificate
              mountPath: /etc/ssl/notary/tls.crt
              subPath: tls.crt
            - name: signer-certificate
              mountPath: /etc/ssl/notary/tls.key
              subPath: tls.key
      volumes:
        - name: config
          secret:
            secretName: "release-name-harbor-notary-server"
        - name: signer-certificate
          secret:
            secretName: release-name-harbor-notary-server
