---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deploy.yml
  - svc.yml

secretGenerator:
  - name: secret-notary-server
    files:
      - certs/ca.crt
      - certs/tls.crt
      - certs/tls.key
      - config/server.json
      - config/signer.json
