---
clair:
  database:
    type: pgsql
    options:
      source: "postgres://%YOUR_DB_USER%:%YOUR_DB_PASSWORD%@%YOUR_DB_HOSTNAME%:%YOUR_DB_PORT%/clair?sslmode=disable"
      # Number of elements kept in the cache
      # Values unlikely to change (e.g. namespaces) are cached in order to save prevent needless roundtrips to the database.
      cachesize: 16384
  api:
    # API server port
    port: 6060
    healthport: 6061
    # Deadline before an API request will respond with a 503
    timeout: 300s
  updater:
    interval: 12h
