---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deploy.yml
  - pvc.yml
  - svc.yml

images:
  - name: goharbor/registry-photon
    newTag: v1.10.2
  - name: goharbor/harbor-registryctl
    newTag: v1.10.2

configMapGenerator:
  - name: registry
    files:
      - config.yml=config/config.yml
      - ctl-config.yml=config/ctl-config.yml

secretGenerator:
  - name: registry
    literals:
      - REGISTRY_HTTP_SECRET=Z6HTqCsLzHMmgr9W
      - REGISTRY_REDIS_PASSWORD=""
