---
apiVersion: v1
kind: Secret
metadata:
  name: "release-name-harbor-registry"
  labels:
    app: "harbor"
type: Opaque
data:
  REGISTRY_HTTP_SECRET: "WjZIVHFDc0x6SE1tZ3I5Vw=="
  REGISTRY_REDIS_PASSWORD: ""
