---
apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: harbor
spec:
  ports:
    - name: registry
      port: 5000
    - name: controller
      port: 8080
  selector:
    app: harbor
    component: registry
