# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: registry

resources:
  - ns.yml

bases:
  - ../../katalog/harbor/distributions/full-harbor

configMapGenerator:
    # ChartMuseum overwritable configuration
  - name: chartmuseum
    behavior: merge
    literals:
      - CACHE_REDIS_ADDR=redis:6379
      - CACHE_REDIS_DB=3
      - BASIC_AUTH_USER=chart_controller
      - DEBUG=false
    # Clair overwritable configuration
  - name: clair
    behavior: merge
    literals:
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - SCANNER_LOG_LEVEL=info
    # Core overwritable configuration
  - name: core
    behavior: merge
    files:
      - app.conf=config/core/app.conf
    literals:
      - POSTGRESQL_HOST=%YOUR_DB_HOSTNAME%
      - POSTGRESQL_PORT=%YOUR_DB_PORT%
      - POSTGRESQL_USERNAME=%YOUR_DB_USER%
      - POSTGRESQL_DATABASE=registry
      - POSTGRESQL_SSLMODE=disable
      - EXT_ENDPOINT=https://harbor.%YOUR_DOMAIN%
      - CLAIR_DB_HOST=%YOUR_DB_HOSTNAME%
      - CLAIR_DB_PORT=%YOUR_DB_PORT%
      - CLAIR_DB_USERNAME=%YOUR_DB_USER%
      - CLAIR_DB=clair
      - CLAIR_DB_SSLMODE=disable
      - LOG_LEVEL=info
      - _REDIS_URL=redis:6379
      - _REDIS_URL_REG=redis://redis:6379/2
      - HTTP_PROXY=
      - HTTPS_PROXY=
    # JobService overwritable configuration
  - name: jobservice
    behavior: merge
    files:
      - config.yml=config/jobservice/config.yml
    literals:
      - LOG_LEVEL=debug
      - HTTP_PROXY=
      - HTTPS_PROXY=
    # Registry overwritable configuration
  - name: registry
    behavior: merge
    files:
      - config.yml=config/registry/config.yml
      - ctl-config.yml=config/registry/ctl-config.yml

secretGenerator:
    # ChartMuseum overwritable configuration
  - name: chartmuseum
    behavior: merge
    literals:
      - CACHE_REDIS_PASSWORD=""
    # Clair overwritable configuration
  - name: clair
    behavior: merge
    files:
      - config.yaml=secrets/clair/config.yaml
    literals:
      - SCANNER_STORE_REDIS_URL=redis://redis:6379
      - SCANNER_CLAIR_DATABASE_URL=postgres://%YOUR_DB_USER%:%YOUR_DB_PASSWORD%@%YOUR_DB_HOSTNAME%:%YOUR_DB_PORT%/clair?sslmode=disable
    # Core overwritable configuration
  - name: core
    behavior: merge
    literals:
      - secretKey=not-a-secure-key
      - secret=P447FhxLeLwjDMYU
      - HARBOR_ADMIN_PASSWORD=Harbor12345
      - POSTGRESQL_PASSWORD=changeit
      - CLAIR_DB_PASSWORD=changeit
    # JobService overwritable configuration
  - name: jobservice
    behavior: merge
    literals:
      - secret=Gx6IsNtY4NdWoK0u
    # Notary overwritable configuration
  - name: notary-server
    behavior: merge
    files:
      - server.json=secrets/notary/server.json
    literals:
      - DB_URL=postgres://%YOUR_DB_USER%:%YOUR_DB_PASSWORD%@%YOUR_DB_HOSTNAME%:%YOUR_DB_PORT%/notaryserver?sslmode=disable
  - name: notary-signer
    behavior: merge
    files:
      - signer.json=secrets/notary/signer.json
    literals:
      - DB_URL=postgres://%YOUR_DB_USER%:%YOUR_DB_PASSWORD%@%YOUR_DB_HOSTNAME%:%YOUR_DB_PORT%/notarysigner?sslmode=disable
    # Registry overwritable configuration
  - name: registry
    behavior: merge
    literals:
      - REGISTRY_HTTP_SECRET=Z6HTqCsLzHMmgr9W
      - REGISTRY_REDIS_PASSWORD=""

patchesJson6902:
  - target:
      group: ""
      version: v1
      kind: PersistentVolumeClaim
      name: pvc-chartmuseum
    path: patch/chartmuseum.yml
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: redis
    path: patch/redis.yml
  - target:
      group: ""
      version: v1
      kind: PersistentVolumeClaim
      name: registry
    path: patch/registry.yml
  - target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: harbor-ingress
    path: patch/ingress.yml
