---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: goharbor/harbor-db
    newTag: v2.0.2

resources:
  - sts.yml
  - svc.yml

secretGenerator:
  - name: database
    literals:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeit
