---
apiVersion: v1
kind: Service
metadata:
  name: clair
  labels:
    app: harbor
spec:
  ports:
    - name: adapter
      port: 8080
    - name: clair
      port: 6060
    - name: clair-health
      port: 6061
  selector:
    app: harbor
    component: clair
