---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor

bases:
  - chartmuseum
  - clair
  - core
  - notary
  - nginx
  - database
  - jobservice
  - portal
  - redis
  - registry
