# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pki.yml
  - deploy.yml
  - svc.yml

images:
  - name: goharbor/harbor-core
    newName: registry.sighup.io/fury/goharbor/harbor-core
    newTag: v2.7.0

configMapGenerator:
  - name: core
    files:
      - app.conf=config/app.conf
    literals:
      - DATABASE_TYPE=postgresql
      - POSTGRESQL_HOST=database
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=registry
      - POSTGRESQL_SSLMODE=disable
      - POSTGRESQL_MAX_IDLE_CONNS=50
      - POSTGRESQL_MAX_OPEN_CONNS=100
      - EXT_ENDPOINT=https://core.harbor.domain
      - CORE_URL=http://core
      - JOBSERVICE_URL=http://jobservice
      - REGISTRY_URL=http://registry:5000
      - TOKEN_SERVICE_URL=http://core/service/token
      - WITH_NOTARY=true
      - NOTARY_URL=http://notary-server:4443
      - CORE_LOCAL_URL=http://127.0.0.1:8080
      - WITH_TRIVY=true
      - TRIVY_ADAPTER_URL=http://trivy-adapter:8080
      - CFG_EXPIRATION=5
      - ADMIRAL_URL=NA
      - REGISTRY_STORAGE_PROVIDER_NAME=filesystem
      - WITH_CHARTMUSEUM=true
      - CHART_REPOSITORY_URL=http://chartmuseum
      - LOG_LEVEL=info
      - CONFIG_PATH=/etc/core/app.conf
      - SYNC_REGISTRY=true
      - CHART_CACHE_DRIVER=redis
      - _REDIS_URL_CORE="redis://redis:6379/0?idle_timeout_seconds=30"
      - _REDIS_URL_REG="redis://redis:6379/2?idle_timeout_seconds=30"
      - PORT=8080
      - PORTAL_URL=http://portal
      - REGISTRYCTL_URL=http://registry:8080
      - REGISTRY_CONTROLLER_URL=http://registry:8080
      - METRIC_ENABLE=true
      - METRIC_NAMESPACE=harbor
      - METRIC_PATH=/metrics
      - METRIC_PORT=8001
      - METRIC_SUBSYSTEM=core
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - NO_PROXY=core,jobservice,database,chartmuseum,trivy,notary-server,notary-signer,registry,portal,exporter,127.0.0.1,localhost,.local,.internal

secretGenerator:
  - name: core
    literals:
      - secretKey=not-a-secure-key
      - secret=P447FhxLeLwjDMYU
      - HARBOR_ADMIN_PASSWORD=Harbor12345
      - POSTGRESQL_PASSWORD=changeit
      - CSRF_KEY=QQRqXf3yTEtceQDS6NMY9F777LZ4bqKt
      - REGISTRY_CREDENTIAL_USERNAME=harbor_registry_user
      - REGISTRY_CREDENTIAL_PASSWORD=DhQTxjwUAyUZHaMABvm90dGAJMDX5jaa
