# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: core-root
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: core-root-ca
spec:
  commonName: core
  dnsNames:
  - core
  isCA: true
  issuerRef:
    kind: Issuer
    name: core-root
  secretName: core-root-ca
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: core-root-ca
spec:
  ca:
    secretName: core-root-ca
