# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: goharbor/harbor-portal
    newName: registry.sighup.io/fury/goharbor/harbor-portal
    newTag: v2.7.0

resources:
  - deploy.yml
  - svc.yml

configMapGenerator:
  - name: portal
    files:
      - nginx.conf=config/nginx.conf
