---
apiVersion: v1
kind: Service
metadata:
  name: portal
  labels:
    app: harbor
    component: portal
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: harbor
    component: portal
