---
# Source: harbor/templates/clair/clair-svc.yaml

apiVersion: v1
kind: Service
metadata:
  name: clair
  labels:
    app: harbor
spec:
  ports:
    - name: adapter
      port: 8080
  selector:
    app: harbor
    component: clair
