# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notary-server
  labels:
    app: harbor
    component: notary-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor
      component: notary-server
  template:
    metadata:
      labels:
        app: harbor
        component: notary-server
    spec:
      securityContext:
        runAsUser: 10000
        fsGroup: 10000
      automountServiceAccountToken: false
      containers:
        - name: notary-server
          image: goharbor/notary-server-photon
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /_notary_server/health
              scheme: "HTTP"
              port: 4443
            initialDelaySeconds: 300
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /_notary_server/health
              scheme: "HTTP"
              port: 4443
            initialDelaySeconds: 20
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: notary-server
            - secretRef:
                name: notary-server
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
          volumeMounts:
            - name: config
              mountPath: /etc/notary/server-config.postgres.json
              subPath: server.json
            - name: token-service-certificate
              mountPath: /root.crt
              subPath: tls.crt
            - name: signer-certificate
              mountPath: /etc/ssl/notary/ca.crt
              subPath: ca.crt
      volumes:
        - name: config
          secret:
            secretName: notary-server
        - name: token-service-certificate
          secret:
            secretName: core-root-ca
        - name: signer-certificate
          secret:
            secretName: notary-signer-cert
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notary-signer
  labels:
    app: harbor
    component: notary-signer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor
      component: notary-signer
  template:
    metadata:
      labels:
        app: harbor
        component: notary-signer
    spec:
      securityContext:
        runAsUser: 10000
        fsGroup: 10000
      automountServiceAccountToken: false
      containers:
        - name: notary-signer
          image: goharbor/notary-signer-photon
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              scheme: "HTTPS"
              port: 7899
            initialDelaySeconds: 300
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              scheme: "HTTPS"
              port: 7899
            initialDelaySeconds: 20
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: notary-signer
            - secretRef:
                name: notary-signer
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
          volumeMounts:
            - name: config
              mountPath: /etc/notary/signer-config.postgres.json
              subPath: signer.json
            - name: signer-certificate
              mountPath: /etc/ssl/notary/tls.crt
              subPath: tls.crt
            - name: signer-certificate
              mountPath: /etc/ssl/notary/tls.key
              subPath: tls.key
      volumes:
        - name: config
          secret:
            secretName: notary-signer
        - name: signer-certificate
          secret:
            secretName: notary-signer-cert
