# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app: harbor
    component: notary-signer
  name: notary-root
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app: harbor
    component: notary-signer
  name: notary-root-ca
spec:
  commonName: notary
  dnsNames:
  - notary
  isCA: true
  issuerRef:
    kind: Issuer
    name: notary-root
  secretName: notary-root-ca
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app: harbor
    component: notary-signer
  name: notary-root-ca
spec:
  ca:
    secretName: notary-root-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app: harbor
    component: notary-signer
  name: notary-signer
spec:
  commonName: notary-signer
  dnsNames:
  - notary-signer
  duration: 2160h0m0s
  issuerRef:
    kind: Issuer
    name: notary-root-ca
  renewBefore: 360h0m0s
  secretName: notary-signer-cert
  usages:
  - server auth
  - client auth
  - digital signature
  - key encipherment
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app: harbor
    component: notary-signer
  name: notary-server
spec:
  commonName: notary-server
  dnsNames:
  - notary-server
  duration: 2160h0m0s
  issuerRef:
    kind: Issuer
    name: notary-root-ca
  renewBefore: 360h0m0s
  secretName: notary-server-cert
  usages:
  - server auth
  - client auth
  - digital signature
  - key encipherment
