# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
version: 0.1
log:
  level: info
  fields:
    service: registry
storage:
  s3:
    region: "%YOUR_OBJECT_STORAGE_REGION%"
    bucket: "%YOUR_OBJECT_STORAGE_BUCKET%"
    regionendpoint: "%YOUR_OBJECT_STORAGE_ENDPOINT%"
    skipverify: %YOUR_OBJECT_STORAGE_SKIP_VERIFY%
    secure: %YOUR_OBJECT_STORAGE_HTTPS%
  cache:
    layerinfo: redis
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
  delete:
    enabled: true
  redirect:
    disable: false
redis:
  addr: "%YOUR_REDIS_HOSTS%"
  sentinelMasterSet: "%YOUR_REDIS_MASTER_SET%"
  db: 2
  readtimeout: 10s
  writetimeout: 10s
  dialtimeout: 10s
  pool:
    maxidle: 100
    maxactive: 500
    idletimeout: 60s
http:
  addr: :5000
  relativeurls: false
  # set via environment variable
  # secret: placeholder
  debug:
    addr: :8001
    prometheus:
      enabled: true
      path: /metrics
auth:
  htpasswd:
    realm: harbor-registry-basic-realm
    path: /etc/registry/passwd
validation:
  disabled: true
compatibility:
  schema1:
    enabled: true
