# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exporter
spec:
  replicas: 1
  revisionHistoryLimit: 10
  template:
    spec:
      securityContext:
        fsGroup: 10000
        runAsUser: 10000
      automountServiceAccountToken: false
      containers:
        - name: exporter
          image: goharbor/harbor-exporter:v2.11.2
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8001
            initialDelaySeconds: 300
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 10
          args: ["-log-level", "info"]
          envFrom:
            - configMapRef:
                name: exporter
            - secretRef:
                name: exporter
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 8001
          volumeMounts:
      volumes:
        - name: config
          secret:
            secretName: exporter
