---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deploy.yml
  - pvc.yml
  - svc.yml

configMapGenerator:
  - name: cm-jobservice
    files:
      - config/config.yml

secretGenerator:
  - name: secret-jobservice
    literals:
      - secret=Gx6IsNtY4NdWoK0u
