---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deploy.yml
  - pvc.yml
  - svc.yml

configMapGenerator:
  - name: cm-jobservice
    literals:
      - CORE_URL=http://release-name-harbor-core
      - REGISTRY_CONTROLLER_URL=http://release-name-harbor-registry
    files:
      - config/config.yml

secretGenerator:
  - name: secret-jobservice
    literals:
      - secret=Gx6IsNtY4NdWoK0u
