---
apiVersion: v1
kind: Service
metadata:
  name: jobservice
  labels:
    app: harbor
    component: jobservice
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: harbor
    component: jobservice
