---
# Source: harbor/templates/nginx/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-harbor-nginx
  labels:
    heritage: Tiller
    release: release-name
    chart: harbor
    app: "harbor"
    component: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      release: release-name
      app: "harbor"
      component: nginx
  template:
    metadata:
      labels:
        heritage: Tiller
        release: release-name
        chart: harbor
        app: "harbor"
        component: nginx
      annotations:
        checksum/configmap: 2e4a15b5d43e4142c394ac8c077c73de78df72ab3f6a78b833255c9e172ffc7b
    spec:
      securityContext:
        fsGroup: 10000
      containers:
        - name: nginx
          image: "goharbor/nginx-photon:v1.10.1"
          imagePullPolicy: "IfNotPresent"
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 10
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 10
          ports:
            - containerPort: 8080
            - containerPort: 8443
            - containerPort: 4443
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: config
          configMap:
            name: release-name-harbor-nginx
