---
apiVersion: v1
kind: Service
metadata:
  name: harbor
  labels:
    app: harbor
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: notary
      port: 4443
      targetPort: 4443
  selector:
    app: harbor
    component: nginx
