apiVersion: v1
stringData:
  SRC_DB_PASSWORD: changeit
  SRC_DB_USER: postgres
  SRC_DB_HOST: database.registry.svc.cluster.local
  SRC_DB_NAME: registry
  SRC_URL: harbor.example.com
  SRC_CREDS: "admin:%HARBOR_ADMIN_PASSWORD%"
  DST_DB_PASSWORD: "%YOUR_DB_PASSWORD%"
  DST_DB_USER: "%YOUR_DB_USER%"
  DST_DB_HOST: "%YOUR_DB_HOSTNAME%"
  DST_DB_NAME: "%YOUR_DB_NAME%"
  DST_URL: harbor-new.example.com
  DST_CREDS: "admin:%HARBOR_ADMIN_PASSWORD%"
kind: Secret
metadata:
  name: db-migration-env
type: Opaque