# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: registry

resources:
- ../../katalog/harbor/distributions/full-harbor

configMapGenerator:
- behavior: merge
  files:
  - app.conf=config/core/app.conf
  literals:
  - POSTGRESQL_HOST=database
  - POSTGRESQL_PORT=5432
  - POSTGRESQL_USERNAME=postgres
  - POSTGRESQL_DATABASE=registry
  - POSTGRESQL_SSLMODE=disable
  - EXT_ENDPOINT=https://harbor.kriive.wtf:1337
  - LOG_LEVEL=debug
  - _REDIS_URL=redis:6379
  - _REDIS_URL_REG=redis://redis:6379/2
  - HTTP_PROXY=
  - HTTPS_PROXY=
  name: core
- behavior: merge
  files:
  - config.yml=config/jobservice/config.yml
  literals:
  - LOG_LEVEL=debug
  - HTTP_PROXY=
  - HTTPS_PROXY=
  name: jobservice
- behavior: merge
  files:
  - config.yml=config/registry/config.yml
  - ctl-config.yml=config/registry/ctl-config.yml
  name: registry
- behavior: merge
  literals:
  - HTTP_PROXY=
  - HTTPS_PROXY=
  - SCANNER_LOG_LEVEL=debug
  - SCANNER_TRIVY_DEBUG_MODE=true
  - SCANNER_TRIVY_VULN_TYPE="os,library"
  - SCANNER_TRIVY_SEVERITY="UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
  - SCANNER_TRIVY_IGNORE_UNFIXED="false"
  name: trivy

    # Database overwritable configuration
    # JobService overwritable configuration
    # trivy overwritable configuration
secretGenerator:
- behavior: merge
  literals:
  - secretKey=not-a-secure-key
  - secret=P447FhxLeLwjDMYU
  - HARBOR_ADMIN_PASSWORD=Harbor12345
  - POSTGRESQL_PASSWORD=changeit
  name: core
- behavior: merge
  literals:
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=changeit
  name: database
- behavior: merge
  literals:
  - secret=Gx6IsNtY4NdWoK0u
  name: jobservice
- behavior: merge
  literals:
  - REGISTRY_HTTP_SECRET=Z6HTqCsLzHMmgr9W
  - REGISTRY_REDIS_PASSWORD=""
  name: registry
- behavior: merge
  literals:
  - SCANNER_TRIVY_GITHUB_TOKEN=
  name: trivy

patches:
- path: patch/database.yml
  target:
    group: apps
    kind: StatefulSet
    name: database
    version: v1
- path: patch/redis.yml
  target:
    group: apps
    kind: StatefulSet
    name: redis
    version: v1
- path: patch/registry.yml
  target:
    kind: PersistentVolumeClaim
    name: registry
    version: v1
- path: patch/ingress.yml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: harbor-ingress
    version: v1
