# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: registry

resources:
  - ../../katalog/harbor/distributions/full-harbor

configMapGenerator:
  # Core overwritable configuration
  - name: core
    behavior: merge
    files:
      - app.conf=config/core/app.conf
    literals:
      - POSTGRESQL_HOST=database
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=registry
      - POSTGRESQL_SSLMODE=disable
      - EXT_ENDPOINT=https://harbor.%YOUR_DOMAIN%:%YOUR_PORT%
      - LOG_LEVEL=debug
      - _REDIS_URL=redis:6379
      - _REDIS_URL_REG=redis://redis:6379/2
      - HTTP_PROXY=
      - HTTPS_PROXY=
    # JobService overwritable configuration
  - name: jobservice
    behavior: merge
    files:
      - config.yml=config/jobservice/config.yml
    literals:
      - LOG_LEVEL=debug
      - HTTP_PROXY=
      - HTTPS_PROXY=
    # Registry overwritable configuration
  - name: registry
    behavior: merge
    files:
      - config.yml=config/registry/config.yml
      - ctl-config.yml=config/registry/ctl-config.yml
    # trivy overwritable configuration
  - name: trivy
    behavior: merge
    literals:
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - SCANNER_LOG_LEVEL=debug
      - SCANNER_TRIVY_DEBUG_MODE=true
      - SCANNER_TRIVY_VULN_TYPE="os,library"
      - SCANNER_TRIVY_SEVERITY="UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
      - SCANNER_TRIVY_IGNORE_UNFIXED="false"

secretGenerator:
  # Core overwritable configuration
  - name: core
    behavior: merge
    literals:
      - secretKey=not-a-secure-key
      - secret=P447FhxLeLwjDMYU
      - HARBOR_ADMIN_PASSWORD=Harbor12345
      - POSTGRESQL_PASSWORD=changeit
    # Database overwritable configuration
  - name: database
    behavior: merge
    literals:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeit
    # JobService overwritable configuration
  - name: jobservice
    behavior: merge
    literals:
      - secret=Gx6IsNtY4NdWoK0u
    # Registry overwritable configuration
  - name: registry
    behavior: merge
    literals:
      - REGISTRY_HTTP_SECRET=Z6HTqCsLzHMmgr9W
      - REGISTRY_REDIS_PASSWORD=""
    # trivy overwritable configuration
  - name: trivy
    behavior: merge
    literals:
      - SCANNER_TRIVY_GITHUB_TOKEN=

patches:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: database
    path: patch/database.yml
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: redis
    path: patch/redis.yml
  - target:
      group: ""
      version: v1
      kind: PersistentVolumeClaim
      name: registry
    path: patch/registry.yml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: harbor-ingress
    path: patch/ingress.yml
