---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    app: harbor
    component: registry
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: harbor
      component: registry
  template:
    metadata:
      labels:
        app: harbor
        component: registry
    spec:
      securityContext:
        fsGroup: 10000
      containers:
        - name: registry
          image: goharbor/registry-photon
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 300
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 1
            periodSeconds: 10
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
          args: ["serve", "/etc/registry/config.yml"]
          envFrom:
            - secretRef:
                name: registry
          ports:
            - containerPort: 5000
            - containerPort: 5001
          volumeMounts:
            - name: data
              mountPath: /storage
            - name: registry-root-certificate
              mountPath: /etc/registry/root.crt
              subPath: tls.crt
            - name: registry-config
              mountPath: /etc/registry/config.yml
              subPath: config.yml
            - name: registry-passwd
              mountPath: /etc/registry/passwd
              subPath: passwd
        - name: registryctl
          image: goharbor/harbor-registryctl
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /api/health
              scheme: HTTP
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              scheme: HTTP
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 10
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
          envFrom:
            - secretRef:
                name: registry
          env:
            - name: CORE_SECRET
              valueFrom:
                secretKeyRef:
                  name: core
                  key: secret
            - name: JOBSERVICE_SECRET
              valueFrom:
                secretKeyRef:
                  name: jobservice
                  key: secret
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /storage
              subPath:
            - name: registry-config
              mountPath: /etc/registry/config.yml
              subPath: config.yml
            - name: registry-config
              mountPath: /etc/registryctl/config.yml
              subPath: ctl-config.yml
      volumes:
        - name: registry-passwd
          secret:
            secretName: registry
        - name: registry-root-certificate
          secret:
            secretName: core-root-ca
        - name: registry-config
          configMap:
            name: registry
        - name: data
          persistentVolumeClaim:
            claimName: registry
