---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: registry
  labels:
    app: harbor
    component: registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
